language: objective-c
osx_image: xcode9.3

branches:
  only:
    - develop
before_install:
  - gem install xcpretty -N
script:
  - xcodebuild -workspace Gigsterous.xcworkspace -scheme Gigsterous -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
